"""Helper functions to locate generated artifacts on disk."""
from pathlib import Path
import re

from app.core.config import settings
from app.core.exeception import AppException, FileNotFoundException

_IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z0-9._-]+$")


def _validate_identifier(value: str, label: str) -> str:
    """Ensure identifiers used in paths only contain safe characters."""
    if not value or not _IDENTIFIER_PATTERN.fullmatch(value):
        raise AppException(
            f"Invalid {label}: {value}. Allowed characters are letters, numbers, '.', '-', and '_'",
            status_code=400,
        )
    return value


def _with_csv_extension(name: str) -> str:
    """Normalize table names so lookups always include the .csv suffix."""
    return name if name.lower().endswith(".csv") else f"{name}.csv"


def get_markdown_file(file_id: str) -> Path:
    """Return the path to the extracted markdown for a document."""
    file_id = _validate_identifier(file_id, "file_id")
    outputs_dir = settings.get_path(settings.OUTPUTS_DIR)
    candidates = [
        outputs_dir / file_id / f"{file_id}.md",
        outputs_dir / file_id / file_id / f"{file_id}.md",
        outputs_dir / f"{file_id}.md",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundException(f"markdown for {file_id}")


def get_raw_table_csv(file_id: str, table_name: str) -> Path:
    """Return a CSV exported by the table extraction stage."""
    file_id = _validate_identifier(file_id, "file_id")
    table_name = _validate_identifier(table_name, "table_id")
    target_filename = _with_csv_extension(table_name)
    doc_dir = settings.get_path(settings.EACH_TABLE_DIR) / file_id
    if not doc_dir.exists():
        raise FileNotFoundException(str(doc_dir))
    candidate = doc_dir / target_filename
    if candidate.exists():
        return candidate
    normalized_stem = Path(target_filename).stem.lower()
    for csv_file in doc_dir.glob("*.csv"):
        if csv_file.stem.lower() == normalized_stem:
            return csv_file
    raise FileNotFoundException(str(candidate))


def get_cleaned_table_csv(file_id: str, table_name: str) -> Path:
    """Return a cleaned CSV generated by the transform2tidy stage."""
    file_id = _validate_identifier(file_id, "file_id")
    table_name = _validate_identifier(table_name, "table_id")
    base_name = table_name
    if not base_name.startswith("cleaned_"):
        base_name = f"cleaned_{base_name}"
    target_filename = _with_csv_extension(base_name)
    doc_dir = settings.get_path(settings.CLEANED_DATA_DIR) / file_id
    if not doc_dir.exists():
        raise FileNotFoundException(str(doc_dir))
    candidate = doc_dir / target_filename
    if candidate.exists():
        return candidate
    normalized_stem = Path(target_filename).stem.lower()
    for csv_file in doc_dir.glob("cleaned_*.csv"):
        if csv_file.stem.lower() == normalized_stem:
            return csv_file
    raise FileNotFoundException(str(candidate))
